name: 'zendesk'
version: '0.4.1'
config-version: 2
require-dbt-version: [">=0.18.0", "<0.20.0"]
on-run-start: '{{ fivetran_utils.empty_variable_warning("ticket_field_history_columns", "zendesk_ticket_field_history") }}'

models:
    zendesk:
        +materialized: table
        agent_work_time:
            +materialized: ephemeral
        intermediate:
            +schema: zendesk_intermediate
            +materialized: table
        reply_times:
            +materialized: ephemeral
        resolution_times:
            +materialized: ephemeral
        sla_policy:
            +schema: zendesk_intermediate
            +materialized: table
        ticket_history:
            +schema: zendesk_intermediate
            +materialized: ephemeral
        utils:
            +materialized: ephemeral

vars:
    zendesk:
        ticket_field_history_columns:   ['assignee_id', 'status', 'priority']
        ticket_field_history_updater_columns: []
        
        group:                  "{{ ref('stg_zendesk__group) }}"
        brand:                  "{{ ref('stg_zendesk__brand') }}"
        domain_name:            "{{ ref('stg_zendesk__domain_name') }}"
        organization_tag:       "{{ ref('stg_zendesk__organization_tag') }}"
        organization:           "{{ ref('stg_zendesk__organization') }}"
        schedule:               "{{ ref('stg_zendesk__schedule') }}"
        ticket:                 "{{ ref('stg_zendesk__ticket') }}"
        ticket_form_history:    "{{ ref('stg_zendesk__ticket_form_history') }}"
        ticket_comment:         "{{ ref('stg_zendesk__ticket_comment') }}"
        field_history:          "{{ ref('stg_zendesk__ticket_field_history') }}"
        ticket_schedule:        "{{ ref('stg_zendesk__ticket_schedule') }}"
        ticket_tag:             "{{ ref('stg_zendesk__ticket_tag') }}"
        user_tag:               "{{ ref('stg_zendesk__user_tag') }}"
        user:                   "{{ ref('stg_zendesk__user') }}"

        using_schedules:            True
        using_domain_names:         True
        using_user_tags:            True
        using_ticket_form_history:  True
        using_organization_tags:    True

        dbt_utils_dispatch_list:
            - fivetran_utils
            - dbt_utils