name: 'zendesk'
version: '0.1.2'
config-version: 2
require-dbt-version: [">=0.18.0", "<0.20.0"]
on-run-start: "{{ ticket_field_history_columns_warning() }}"

models:
    zendesk:
        +materialized: table
        agent_work_time:
            +materialized: table
        intermediate:
            +materialized: table
        reply_times:
            +materialized: table
        resolution_times:
            +materialized: table
        sla_policy:
            +materialized: table
        ticket_history:
            +materialized: table
        utils:
            +materialized: table

vars:
    zendesk:
        ticket_field_history_columns:   [ 'assignee_id', 'status', 'priority' ]
        group:                  "{{ ref('stg_zendesk__group) }}"
        brand:                  "{{ ref('stg_zendesk__brand') }}"
        domain_name:            "{{ ref('stg_zendesk__domain_name') }}"
        organization_tag:       "{{ ref('stg_zendesk__organization_tag') }}"
        organization:           "{{ ref('stg_zendesk__organization') }}"
        schedule:               "{{ ref('stg_zendesk__schedule') }}"
        satisfaction_rating:    "{{ ref('stg_zendesk__satisfaction_rating') }}"
        ticket:                 "{{ ref('stg_zendesk__ticket') }}"
        ticket_form_history:    "{{ ref('stg_zendesk__ticket_form_history') }}"
        ticket_comment:         "{{ ref('stg_zendesk__ticket_comment') }}"
        field_history:          "{{ ref('stg_zendesk__ticket_field_history') }}"
        ticket_schedule:        "{{ ref('stg_zendesk__ticket_schedule') }}"
        ticket_tag:             "{{ ref('stg_zendesk__ticket_tag') }}"
        user_tag:               "{{ ref('stg_zendesk__user_tag') }}"
        user:                   "{{ ref('stg_zendesk__user') }}"

        dbt_utils_dispatch_list:
            - zendesk 
            - dbt_utils