config-version: 2

name: 'zendesk'
version: '0.0.1'

profile: 'fivetran'


models:
    zendesk:
        materialized: table
        base:
            materialized: table
        intermediate:
            materialized: table 

    zendesk_source:
        vars:
            zendesk_schema: 'zendesk'  